import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // === LeaveSync palette ===
        'inverse-primary': '#c1c1ff',
        'secondary': '#5d5c76',
        'secondary-container': '#e0dcfb',
        'on-secondary-container': '#62607a',
        'secondary-fixed': '#e3dffe',
        'secondary-fixed-dim': '#c7c3e2',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1a1930',
        'on-secondary-fixed-variant': '#46445d',

        'primary': '#4b4bc6',
        'primary-container': '#6466e1',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#e1dfff',
        'primary-fixed-dim': '#c1c1ff',
        'on-primary-fixed': '#08006c',
        'on-primary-fixed-variant': '#3433b0',
        'surface-tint': '#4d4ec9',

        'tertiary': '#835100',
        'tertiary-container': '#a56700',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffddb9',
        'tertiary-fixed-dim': '#ffb963',
        'on-tertiary-fixed': '#2b1700',
        'on-tertiary-fixed-variant': '#663e00',

        'background': '#f9f9fa',
        'on-background': '#1a1c1d',
        'surface': '#f9f9fa',
        'on-surface': '#1a1c1d',
        'surface-white': '#FFFFFF',
        'surface-dim': '#dadadb',
        'surface-bright': '#f9f9fa',
        'surface-variant': '#e2e2e3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeef',
        'surface-container-high': '#e8e8e9',
        'surface-container-highest': '#e2e2e3',
        'on-surface-variant': '#464553',

        'outline': '#777585',
        'outline-variant': '#c7c5d6',

        'inverse-surface': '#2f3132',
        'inverse-on-surface': '#f0f1f2',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'error-red': '#F04438',

        'warning-amber': '#F79009',
        'success-green': '#12B76A',
        'brand-pink': '#EA4C89',

        // === Legacy aliases (kept so existing pages don't break) ===
        'success': '#12B76A',
        'on-success': '#ffffff',
        'success-container': '#d1fadf',
        'on-success-container': '#065f46',
        'warning': '#F79009',
        'on-warning': '#ffffff',
        'warning-container': '#fef3c7',
        'on-warning-container': '#78350f',
        'border-subtle': '#e5e7eb',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-lg': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
      },
      spacing: {
        'sidebar-width': '280px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'gutter': '24px',
        'margin-page': '32px',
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
export default config
